id: A8911F3F4
title: Concise Consecration
type: translation
pechas:
- I462EA04C
- IA8ADD870
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:47:26.162673
  last_modified_at: 2023-01-04 11:47:26.162688
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I462EA04C/763D: D4A2
  IA8ADD870/5A70: D4A2
